-- INSERINDO DADOS NO BANCO

INSERT INTO tabelacadastro(ID, NOME, AGENCIACODE, NUMEROCONTA, DIGITO, IDREGISTRO) VALUES (1, 'AROLDO', '1234', '123456', '5', '1'); 
INSERT INTO tabelacadastro(ID, NOME, AGENCIACODE, NUMEROCONTA, DIGITO, IDREGISTRO) VALUES (2, 'CRISTI', '5678', '789101', '1', '2');
INSERT INTO tabelacadastro(ID, NOME, AGENCIACODE, NUMEROCONTA, DIGITO, IDREGISTRO) VALUES (3, 'JESSIC', '9101', '654321', '2', '3');
INSERT INTO tabelacadastro(ID, NOME, AGENCIACODE, NUMEROCONTA, DIGITO, IDREGISTRO) VALUES (4, 'DANIEL', '0987', '098765', '3', '4');
INSERT INTO tabelacadastro(ID, NOME, AGENCIACODE, NUMEROCONTA, DIGITO, IDREGISTRO) VALUES (5, 'ROBERT', '1341', '134498', '4', '5');