-- INSERINDO DADOS NO BANCO

INSERT INTO TABELA_CADASTRO(ID, NOME, SOBRENOME, AGENCIACODE, NUMEROCONTA, DIGITO) VALUES (1, 'AROLDO', 'DE SOUZA JOAO', '1234', '123456', '5'); 
INSERT INTO TABELA_CADASTRO(ID, NOME, SOBRENOME, AGENCIACODE, NUMEROCONTA, DIGITO) VALUES (2, 'CRISTIANE','DE SOUZA IKEDA', 5678, 789101, '1');
INSERT INTO TABELA_CADASTRO(ID, NOME, SOBRENOME, AGENCIACODE, NUMEROCONTA, DIGITO) VALUES (3, 'JESSICA', 'MARTINS', 9101, 654321, '2');
INSERT INTO TABELA_CADASTRO(ID, NOME, SOBRENOME, AGENCIACODE, NUMEROCONTA, DIGITO) VALUES (4, 'DANIELE', 'BRAGA', 0987, 098765, '3');
INSERT INTO TABELA_CADASTRO(ID, NOME, SOBRENOME, AGENCIACODE, NUMEROCONTA, DIGITO) VALUES (5, 'ROBERTO', 'JOAO', 1341, 134498, '4');