version: 0.2

phases:
  build:
    commands:
      - echo Entrando no build phase...
      - mvn clean package
  post_build:
    commands:
      - echo Build Finalizaso com sucesso
artifacts:
  files:
    - target/desafio.jar
  discard-paths: yes